apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-xen-volume
  namespace: csi-test 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: xen-orchestra-storage
# allowVolumeExpansion: true
