kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base/

images:
- digest: sha256:ad1034e9acaa20d618b13b8beafaa6f4c3f5e115c99b9a2931f42ae8e66f3f83
  name: csi-xen-orchestra-driver
  newName: ghcr.io/m4rcsi/csi-xen-orchestra-driver
