kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base/

images:
- digest: sha256:f0e67a9ce55680015e59bfb2580db9154b789c643141cd10775798230f5e94af
  name: csi-xen-orchestra-driver
  newName: ghcr.io/m4rcsi/csi-xen-orchestra-driver
