kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base/

images:
- digest: sha256:9b331e2fb437d917ec752366d3fb43c08c59d053a832af2766c28b053cbcb3ac
  name: csi-xen-orchestra-driver
  newName: ghcr.io/m4rcsi/csi-xen-orchestra-driver
