kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base/

images:
- digest: sha256:5c0365682f7a538aa07c30d71a5041d86fa6c864bf8fc986df21ce79c2a0fad1
  name: csi-xen-orchestra-driver
  newName: ghcr.io/m4rcsi/csi-xen-orchestra-driver
