kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base/

images:
- digest: sha256:37e9a8c3455da18c7ad4a6ca3ba1708928fb5ccb19ee1776c9c533eb076ead25
  name: csi-xen-orchestra-driver
  newName: ghcr.io/m4rcsi/csi-xen-orchestra-driver
