kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base/

images:
- digest: sha256:f5f8607309767cddb0e9a565045f507bf9ac7c33f6041a069dcd1e0689b963dc
  name: csi-xen-orchestra-driver
  newName: ghcr.io/m4rcsi/csi-xen-orchestra-driver


patches:
# More verbose logging for controller
- patch: |-
    - op: add
      path: /spec/template/spec/containers/3/args/-
      value: "--v=4"
  target:
    kind: Deployment
    name: csi-xen-orchestra-controller
# More verbose logging for node
- patch: |-
    - op: add
      path: /spec/template/spec/containers/1/args/-
      value: "--v=4"
  target:
    kind: DaemonSet
    name: csi-xen-orchestra-node
# Set custom the disk name prefix
# - patch: |-
#     - op: add
#       path: /spec/template/spec/containers/3/args/-
#       value: "--disk-name-prefix=csistaging-"
#   target:
#     kind: Deployment
#     name: csi-xen-orchestra-controller
