kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base/

images:
- digest: sha256:3096ae91272a16cb0a15aff96135814d0a52724547efbc28e94ed9779be73697
  name: csi-xen-orchestra-driver
  newName: ghcr.io/m4rcsi/csi-xen-orchestra-driver

# Set custom the disk name prefix
# - patch: |-
#     - op: add
#       path: /spec/template/spec/containers/3/args/-
#       value: "--disk-name-prefix=csistaging-"
#   target:
#     kind: Deployment
#     name: csi-xen-orchestra-controller
