apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-static-pv
  namespace: csi-test
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: csi.xen-orchestra.marcsi.ch
    volumeHandle: 8d5b7ab2-db4f-4894-a444-567e61e4aa54 # this is the VDI UUID
