apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-static-pvc
  namespace: csi-test
spec:
  volumeName: test-static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
