apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: xoa-shared
provisioner: csi.xen-orchestra.marcsi.ch
parameters:
  srWithTag: k8s-shared
volumeBindingMode: Immediate
allowVolumeExpansion: true