kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base/

images:
- name: csi-xen-orchestra-driver
  newName: ghcr.io/m4rcsi/csi-xen-orchestra-driver
  newTag: v0.1.0

# patches:
# # Enable temp cleanup for controller
# - patch: |-
#     - op: add
#       path: /spec/template/spec/containers/3/args/-
#       value: "--temp-cleanup=true"
#   target:
#     kind: Deployment
#     name: csi-xen-orchestra-controller

# # Set custom the disk name prefix
# - patch: |-
#     - op: add
#       path: /spec/template/spec/containers/3/args/-
#       value: "--disk-name-prefix=csicustom-"
#   target:
#     kind: Deployment
#     name: csi-xen-orchestra-controller